name:                mau-mau-BE
version:             0.1.0.0
github:              "JiriLojda/mau-mau-BE"
license:             BSD3
author:              "JiriLojda"
maintainer:          "lojdaj@seznam.cz"
copyright:           "2023 Jiri Lojda"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JiriLojda/mau-mau-BE#readme>

dependencies:
- base >= 4.7 && < 5

language: GHC2021

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- StrictData
- OverloadedRecordDot
- DuplicateRecordFields


library:
  source-dirs: src
  dependencies:
  - websockets
  - text
  - stm
  - containers
  - bytestring
  - aeson
  - uuid
  - random
  - extra

executables:
  mau-mau-BE-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mau-mau-BE

tests:
  mau-mau-BE-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mau-mau-BE
    - hspec
    - hspec-discover
    - QuickCheck
    - containers
    - text
    - hedgehog
    - hspec-hedgehog
